name: 'CI / Linux'

on:
  push:
    branches:
      - development
      - linux
      - 'linux-release-*'
    tags:
      - 'release-*.*.*-linux*'
      - 'release-*.*.*-test*'
  pull_request:
    branches:
      - linux
      - linux-vnext
      - 'linux-release-*'

env:
  NODE_VERSION: 24.11.1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: node vendor/yarn-1.21.1.js install

      - run: node vendor/yarn-1.21.1.js validate-electron-version
      - run: node vendor/yarn-1.21.1.js lint
      - run: node vendor/yarn-1.21.1.js validate-changelog

      - name: Ensure a clean working directory
        run: git diff --name-status --exit-code

  amd64:
    name: Ubuntu x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-dev libxss-dev fakeroot dpkg

      - name: Install dependencies
        run: node vendor/yarn-1.21.1.js install

      - name: Build production
        run: node vendor/yarn-1.21.1.js build:prod

      - name: Package
        run: node vendor/yarn-1.21.1.js run package

      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-amd64-artifacts
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.sha256
          retention-days: 5
          if-no-files-found: error

  publish:
    name: Create GitHub release
    needs: [amd64]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: './artifacts'

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: './artifacts'

      - name: Get tag name without prefix
        run: |
          RELEASE_TAG=${GITHUB_REF/refs\/tags\//}
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          tagNameWithoutPrefix="${RELEASE_TAG:8}"
          echo "RELEASE_TAG_WITHOUT_PREFIX=${tagNameWithoutPrefix}" >> $GITHUB_ENV

      - name: Generate release notes
        run: |
          node -v
          node vendor/yarn-1.21.1.js install
          node --import tsx script/generate-release-notes.ts "${{ github.workspace }}/artifacts" "${{ env.RELEASE_TAG_WITHOUT_PREFIX }}"
          RELEASE_NOTES_FILE=script/release_notes.txt
          if [[ ! -f "$RELEASE_NOTES_FILE" ]]; then
              echo "$RELEASE_NOTES_FILE does not exist. Something might have gone wrong while generating the release notes."
              exit 1
          fi
          echo "Release notes:"
          echo "---"
          cat ${RELEASE_NOTES_FILE}
          echo "---"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: GitHub Desktop for Linux ${{ env.RELEASE_TAG_WITHOUT_PREFIX }}
          body_path: script/release_notes.txt
          files: |
            artifacts/**/*.AppImage
            artifacts/**/*.deb
            artifacts/**/*.sha256
          draft: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
